# Generated by Django 3.2.3 on 2021-05-31 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_customer_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('ORDERED', 'ORDERED'), ('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED'), ('SHIPPING', 'SHIPPING'), ('ARRIVING', 'ARRIVING')], max_length=150)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.product')),
            ],
        ),
    ]
